#!/bin/sh
#
# summary of how this script can be called:
#        * <new-preinst> install
#        * <new-preinst> install <old-version>
#        * <new-preinst> upgrade <old-version>
#        * <old-preinst> abort-upgrade <new-version>
#

set -e

. /usr/share/debconf/confmodule

CONFFILE=/etc/igestis/config.php

# We move old style config file.
if [ -e "$CONFFILE" ] ; then
    mkdir -p /var/backup/igestis/ && chmod 700 /var/backup/igestis/
    mv $CONFFILE /var/backup/igestis/config.php
fi

#DEBHELPER#
exit 0


